#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*          This image has been deprecated            *
*                                                    *
*              Use the new image at                  *
*                                                    *
*                linuxserver/mylar3                  *
*                                                    *
*    https://hub.docker.com/r/linuxserver/mylar3     *
*                                                    *
*   https://github.com/linuxserver/docker-mylar3     *
*                                                    *
*                                                    *
*                                                    *
******************************************************
******************************************************'